/*
 * generated by Xtext 2.27.0
 */
package de.fraunhofer.ipa.deployment.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import de.fraunhofer.ipa.deployment.DeployModelRuntimeModule;
import de.fraunhofer.ipa.deployment.DeployModelStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class DeployModelIdeSetup extends DeployModelStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new DeployModelRuntimeModule(), new DeployModelIdeModule()));
	}
	
}
