/*
 * generated by Xtext 2.27.0
 */
package de.fraunhofer.ipa.deployment.ide;


/**
 * Use this class to register ide components.
 */
public class DeployModelIdeModule extends AbstractDeployModelIdeModule {
}
