/*
 * generated by Xtext 2.27.0
 */
package de.fraunhofer.ipa.deployment;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class DeployModelRuntimeModule extends AbstractDeployModelRuntimeModule {
}
