/*
 * generated by Xtext 2.27.0
 */
package de.fraunhofer.ipa.deployment.parser.antlr;

import de.fraunhofer.ipa.deployment.parser.antlr.internal.InternalDeployModelParser;
import org.antlr.runtime.Token;
import org.antlr.runtime.TokenSource;
import org.eclipse.xtext.parser.antlr.AbstractIndentationTokenSource;

public class DeployModelTokenSource extends AbstractIndentationTokenSource {

	public DeployModelTokenSource(TokenSource delegate) {
		super(delegate);
	}

	@Override
	protected boolean shouldSplitTokenImpl(Token token) {
		// TODO Review assumption
		return token.getType() == InternalDeployModelParser.RULE_WS;
	}

	@Override
	protected int getBeginTokenType() {
		// TODO Review assumption
		return InternalDeployModelParser.RULE_INDENT;
	}

	@Override
	protected int getEndTokenType() {
		// TODO Review assumption
		return InternalDeployModelParser.RULE_DEDENT;
	}

}
