/**
 * generated by Xtext 2.27.0
 */
package de.fraunhofer.ipa.deployment.deployModel.tests;

import de.fraunhofer.ipa.deployment.deployModel.DeployModelFactory;
import de.fraunhofer.ipa.deployment.deployModel.MultiMonolithicImplementationNamePreList;

import junit.textui.TestRunner;

/**
 * <!-- begin-user-doc -->
 * A test case for the model object '<em><b>Multi Monolithic Implementation Name Pre List</b></em>'.
 * <!-- end-user-doc -->
 * @generated
 */
public class MultiMonolithicImplementationNamePreListTest extends MultiMonolithicImplementationNameListTest {

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public static void main(String[] args) {
		TestRunner.run(MultiMonolithicImplementationNamePreListTest.class);
	}

	/**
	 * Constructs a new Multi Monolithic Implementation Name Pre List test case with the given name.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public MultiMonolithicImplementationNamePreListTest(String name) {
		super(name);
	}

	/**
	 * Returns the fixture for this Multi Monolithic Implementation Name Pre List test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	protected MultiMonolithicImplementationNamePreList getFixture() {
		return (MultiMonolithicImplementationNamePreList)fixture;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#setUp()
	 * @generated
	 */
	@Override
	protected void setUp() throws Exception {
		setFixture(DeployModelFactory.eINSTANCE.createMultiMonolithicImplementationNamePreList());
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#tearDown()
	 * @generated
	 */
	@Override
	protected void tearDown() throws Exception {
		setFixture(null);
	}

} //MultiMonolithicImplementationNamePreListTest
