/**
 * generated by Xtext 2.27.0
 */
package de.fraunhofer.ipa.deployment.deployModel.tests;

import de.fraunhofer.ipa.deployment.deployModel.DeployModelFactory;
import de.fraunhofer.ipa.deployment.deployModel.MultiMonolithicImplementationNameList;

import junit.framework.TestCase;

import junit.textui.TestRunner;

/**
 * <!-- begin-user-doc -->
 * A test case for the model object '<em><b>Multi Monolithic Implementation Name List</b></em>'.
 * <!-- end-user-doc -->
 * @generated
 */
public class MultiMonolithicImplementationNameListTest extends TestCase {

	/**
	 * The fixture for this Multi Monolithic Implementation Name List test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MultiMonolithicImplementationNameList fixture = null;

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public static void main(String[] args) {
		TestRunner.run(MultiMonolithicImplementationNameListTest.class);
	}

	/**
	 * Constructs a new Multi Monolithic Implementation Name List test case with the given name.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public MultiMonolithicImplementationNameListTest(String name) {
		super(name);
	}

	/**
	 * Sets the fixture for this Multi Monolithic Implementation Name List test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected void setFixture(MultiMonolithicImplementationNameList fixture) {
		this.fixture = fixture;
	}

	/**
	 * Returns the fixture for this Multi Monolithic Implementation Name List test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MultiMonolithicImplementationNameList getFixture() {
		return fixture;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#setUp()
	 * @generated
	 */
	@Override
	protected void setUp() throws Exception {
		setFixture(DeployModelFactory.eINSTANCE.createMultiMonolithicImplementationNameList());
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#tearDown()
	 * @generated
	 */
	@Override
	protected void tearDown() throws Exception {
		setFixture(null);
	}

} //MultiMonolithicImplementationNameListTest
