/**
 * generated by Xtext 2.27.0
 */
package de.fraunhofer.ipa.deployment.deployModel.tests;

import de.fraunhofer.ipa.deployment.deployModel.DeployModelFactory;
import de.fraunhofer.ipa.deployment.deployModel.MultiMonolithicImplementationNameListBracket;

import junit.textui.TestRunner;

/**
 * <!-- begin-user-doc -->
 * A test case for the model object '<em><b>Multi Monolithic Implementation Name List Bracket</b></em>'.
 * <!-- end-user-doc -->
 * @generated
 */
public class MultiMonolithicImplementationNameListBracketTest extends MultiMonolithicImplementationNameListTest {

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public static void main(String[] args) {
		TestRunner.run(MultiMonolithicImplementationNameListBracketTest.class);
	}

	/**
	 * Constructs a new Multi Monolithic Implementation Name List Bracket test case with the given name.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public MultiMonolithicImplementationNameListBracketTest(String name) {
		super(name);
	}

	/**
	 * Returns the fixture for this Multi Monolithic Implementation Name List Bracket test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	protected MultiMonolithicImplementationNameListBracket getFixture() {
		return (MultiMonolithicImplementationNameListBracket)fixture;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#setUp()
	 * @generated
	 */
	@Override
	protected void setUp() throws Exception {
		setFixture(DeployModelFactory.eINSTANCE.createMultiMonolithicImplementationNameListBracket());
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#tearDown()
	 * @generated
	 */
	@Override
	protected void tearDown() throws Exception {
		setFixture(null);
	}

} //MultiMonolithicImplementationNameListBracketTest
