/**
 * generated by Xtext 2.27.0
 */
package de.fraunhofer.ipa.deployment.deployModel.tests;

import de.fraunhofer.ipa.deployment.deployModel.DeployModelFactory;
import de.fraunhofer.ipa.deployment.deployModel.NewImplementationArtifact;

import junit.framework.TestCase;

import junit.textui.TestRunner;

/**
 * <!-- begin-user-doc -->
 * A test case for the model object '<em><b>New Implementation Artifact</b></em>'.
 * <!-- end-user-doc -->
 * @generated
 */
public class NewImplementationArtifactTest extends TestCase {

	/**
	 * The fixture for this New Implementation Artifact test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NewImplementationArtifact fixture = null;

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public static void main(String[] args) {
		TestRunner.run(NewImplementationArtifactTest.class);
	}

	/**
	 * Constructs a new New Implementation Artifact test case with the given name.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public NewImplementationArtifactTest(String name) {
		super(name);
	}

	/**
	 * Sets the fixture for this New Implementation Artifact test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected void setFixture(NewImplementationArtifact fixture) {
		this.fixture = fixture;
	}

	/**
	 * Returns the fixture for this New Implementation Artifact test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NewImplementationArtifact getFixture() {
		return fixture;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#setUp()
	 * @generated
	 */
	@Override
	protected void setUp() throws Exception {
		setFixture(DeployModelFactory.eINSTANCE.createNewImplementationArtifact());
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#tearDown()
	 * @generated
	 */
	@Override
	protected void tearDown() throws Exception {
		setFixture(null);
	}

} //NewImplementationArtifactTest
