/*
 * generated by Xtext 2.27.0
 */
package de.fraunhofer.ipa.deployment.ui.contentassist;


/**
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#content-assist
 * on how to customize the content assistant.
 */
public class DeployModelProposalProvider extends AbstractDeployModelProposalProvider {
}
